### ISSUE TITLE
Not able to change ynab token when putting in wrong token

### ISSUE THREAD

**Issue by thorep** [Wedvich/sbanken-ynab#8] opened 2020-08-23 11:22 UTC

**Comment by Wedvich** [comment] 2020-08-24 11:40
Oh, not good! Will check it out. As a workaround in the meantime, could you try clearing out the local data? `localStorage.clear()` (and `sessionStorage.clear()` if needed) should do the trick and let you restart the onboarding.

**Comment by Wedvich** [comment] 2020-08-24 20:09
Can you describe where/what you were doing to get to that state? When I try to reproduce it with the latest version now (both locally and on https://sbanken-ynab.azurewebsites.net) I get this error message:
![image](https://user-images.githubusercontent.com/1078076/91091068-596b4680-e656-11ea-870c-9fb2f0bc4013.png)

**Comment by thorep** [comment] 2020-08-25 08:39
i put in the correct sbanken key, got to the next screen where i need to put in ynab key. I accidentally put in the wrong key her, not the correct one. I see in console in chrome that it cant connect..and its just stuck there..

**Comment by Wedvich** [comment] 2020-08-25 09:07
Ooo sorry, I misread, I thought you were talking about the Sbanken screen! I'll add handling errors for Ynab as well.

**Comment by Wedvich** [comment] 2020-08-26 06:57
This should be fixed now with edd271f89887ab2eb7f058378aa38054fe8aec39, and you should get a similar error message to the Sbanken screen and the chance to retry. Could you try it to verify it's fixed? You might need to hard refresh the page since an older version could be cached.

**Comment by thorep** [comment] 2020-08-26 08:04
Tried cloning the project again, but now there is something else wrong. Yarn install dont install any packages

**Closed** 2022-01-20 20:32 UTC
